export const nonStandardSchema = {
    name: "Non-Standard Protocol",
    startState: 'q0',
    weight: 60,
    acceptedStates: new Set(['q_accept']),
    transitions: {
        'q0': { 'f': 'q_f1', 'd': 'q_d1', 'j': 'q_j1', 'w': 'q_w1', '*': 'q0' },
        'q_f1': { 't': 'q_ft1', 'i': 'q_fi1', '*': 'q0' },
        'q_ft1': { 'p': 'q_ft2', '*': 'q0' },
        'q_ft2': { ':': 'q_accept', '*': 'q0' },
        'q_fi1': { 'l': 'q_fi2', '*': 'q0' },
        'q_fi2': { 'e': 'q_fi3', '*': 'q0' },
        'q_fi3': { ':': 'q_accept', '*': 'q0' },
        'q_d1': { 'a': 'q_d2', '*': 'q0' },
        'q_d2': { 't': 'q_d3', '*': 'q0' },
        'q_d3': { 'a': 'q_d4', '*': 'q0' },
        'q_d4': { ':': 'q_accept', '*': 'q0' },
        'q_w1': { 's': 'q_w2', '*': 'q0' },
        'q_w2': { ':': 'q_accept', 's': 'q_w3', '*': 'q0' }, 
        'q_w3': { ':': 'q_accept', '*': 'q0' },
        'q_j1': { 'a': 'q_j2', '*': 'q0' },
        'q_j2': { 'v': 'q_j3', '*': 'q0' },
        'q_j3': { 'a': 'q_j4', '*': 'q0' },
        'q_j4': { 's': 'q_j5', '*': 'q0' },
        'q_j5': { 'c': 'q_j6', '*': 'q0' },
        'q_j6': { 'r': 'q_j7', '*': 'q0' },
        'q_j7': { 'i': 'q_j8', '*': 'q0' },
        'q_j8': { 'p': 'q_j9', '*': 'q0' },
        'q_j9': { 't': 'q_j10', '*': 'q0' },
        'q_j10': { ':': 'q_accept', '*': 'q0' },
        'q_accept': { '*': 'q_accept' }
    },
    target: 'full'
}